app = "people-analytics-backend"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8001"
  PYTHON_VERSION = "3.9"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[deploy]
  release_command = "echo 'Deployment complete'"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512