services:
  - type: web
    name: people-analytics-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: MONGO_URL
        sync: false  # Set manually in Render dashboard
      - key: DB_NAME
        value: people_analytics
      - key: CORS_ORIGINS
        sync: false  # Set manually in Render dashboard
      - key: EMERGENT_LLM_KEY
        sync: false  # Set manually in Render dashboard